# Generated by Django 2.2.2 on 2019-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190613_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(default='general', on_delete='DO_NOTHING', to='todo.Category'),
        ),
    ]
